package android.src.main.kotlin.com.tmapmobility.tmap.tmapsdk.flutter.tmap_ui_sdk.model

enum class TmapDriveStatusModel(val text: String) {
    NotDriving("notDriving"),
    OnAlternativeRouteChanged("onAlternativeRouteChanged"),
    OnApproachingDestination("onApproachingDestination"),
    OnArrivedDestination("onArrivedDestination"),
    OnBreakawayFromRouteEvent("onBreakawayFromRouteEvent"),
    OnApproachingAlternativeRoute("onApproachingAlternativeRoute"),
    OnPassedAlternativeRouteJunction("onPassedAlternativeRouteJunction"),
    OnPeriodicReroute("onPeriodicReroute"),
    OnRouteChanged("onRouteChanged"),
    OnForceReroute("onForceReroute"),
    OnNoLocationSignal("onNoLocationSignal"),
    OnApproachingViaPoint("onApproachingViaPoint"),
    OnApproachingViaOrDestination("onApproachingViaOrDestination"),
    OnPassedViaPoint("onPassedViaPoint"),
    OnChangeRouteOptionComplete("onChangeRouteOptionComplete"),
    OnBreakAwayRequestComplete("onBreakAwayRequestComplete"),
    OnPeriodicRerouteComplete("onPeriodicRerouteComplete"),
    OnUserRerouteComplete("onUserRerouteComplete"),
    OnForceRerouteComplete("onForceRerouteComplete"),
    OnDestinationDirResearchComplete("onDestinationDirResearchComplete"),
    DoNotDestinationDirSearchFromNowOn("doNotDestinationDirSearchFromNowOn"),
    OnFailRouteRequest("onFailRouteRequest"),
    OnPassedTollgate("onPassedTollgate"),
    OnFinishRouteRequestOnComplete("onFinishRouteRequestOnComplete"),
    OnReroute("onReroute"),
    OnRerouteComplete("onRerouteComplete"),
    OnRerouteFailed("onRerouteFailed"),
    OnIgnoringDisabledReroute("onIgnoringDisabledReroute"),
    PassedDestinationOpposite("passedDestinationOpposite"),
    OnNewRerouteIsIgnoredDuringRerouting("onNewRerouteIsIgnoredDuringRerouting"),
}
